//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoesWebApplication.JoesServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JoesServiceReference.JoesWebServiceSoap")]
    public interface JoesWebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        JoesWebApplication.JoesServiceReference.HelloWorldResponse HelloWorld(JoesWebApplication.JoesServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<JoesWebApplication.JoesServiceReference.HelloWorldResponse> HelloWorldAsync(JoesWebApplication.JoesServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usr del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldByUser", ReplyAction="*")]
        JoesWebApplication.JoesServiceReference.HelloWorldByUserResponse HelloWorldByUser(JoesWebApplication.JoesServiceReference.HelloWorldByUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldByUser", ReplyAction="*")]
        System.Threading.Tasks.Task<JoesWebApplication.JoesServiceReference.HelloWorldByUserResponse> HelloWorldByUserAsync(JoesWebApplication.JoesServiceReference.HelloWorldByUserRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento authToken del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldByToken", ReplyAction="*")]
        JoesWebApplication.JoesServiceReference.HelloWorldByTokenResponse HelloWorldByToken(JoesWebApplication.JoesServiceReference.HelloWorldByTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldByToken", ReplyAction="*")]
        System.Threading.Tasks.Task<JoesWebApplication.JoesServiceReference.HelloWorldByTokenResponse> HelloWorldByTokenAsync(JoesWebApplication.JoesServiceReference.HelloWorldByTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public JoesWebApplication.JoesServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(JoesWebApplication.JoesServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public JoesWebApplication.JoesServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(JoesWebApplication.JoesServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldByUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldByUser", Namespace="http://tempuri.org/", Order=0)]
        public JoesWebApplication.JoesServiceReference.HelloWorldByUserRequestBody Body;
        
        public HelloWorldByUserRequest() {
        }
        
        public HelloWorldByUserRequest(JoesWebApplication.JoesServiceReference.HelloWorldByUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldByUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public HelloWorldByUserRequestBody() {
        }
        
        public HelloWorldByUserRequestBody(string usr, string pwd) {
            this.usr = usr;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldByUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldByUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public JoesWebApplication.JoesServiceReference.HelloWorldByUserResponseBody Body;
        
        public HelloWorldByUserResponse() {
        }
        
        public HelloWorldByUserResponse(JoesWebApplication.JoesServiceReference.HelloWorldByUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldByUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldByUserResult;
        
        public HelloWorldByUserResponseBody() {
        }
        
        public HelloWorldByUserResponseBody(string HelloWorldByUserResult) {
            this.HelloWorldByUserResult = HelloWorldByUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldByTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldByToken", Namespace="http://tempuri.org/", Order=0)]
        public JoesWebApplication.JoesServiceReference.HelloWorldByTokenRequestBody Body;
        
        public HelloWorldByTokenRequest() {
        }
        
        public HelloWorldByTokenRequest(JoesWebApplication.JoesServiceReference.HelloWorldByTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldByTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authToken;
        
        public HelloWorldByTokenRequestBody() {
        }
        
        public HelloWorldByTokenRequestBody(string authToken) {
            this.authToken = authToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldByTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldByTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public JoesWebApplication.JoesServiceReference.HelloWorldByTokenResponseBody Body;
        
        public HelloWorldByTokenResponse() {
        }
        
        public HelloWorldByTokenResponse(JoesWebApplication.JoesServiceReference.HelloWorldByTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldByTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldByTokenResult;
        
        public HelloWorldByTokenResponseBody() {
        }
        
        public HelloWorldByTokenResponseBody(string HelloWorldByTokenResult) {
            this.HelloWorldByTokenResult = HelloWorldByTokenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JoesWebServiceSoapChannel : JoesWebApplication.JoesServiceReference.JoesWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JoesWebServiceSoapClient : System.ServiceModel.ClientBase<JoesWebApplication.JoesServiceReference.JoesWebServiceSoap>, JoesWebApplication.JoesServiceReference.JoesWebServiceSoap {
        
        public JoesWebServiceSoapClient() {
        }
        
        public JoesWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JoesWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JoesWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JoesWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JoesWebApplication.JoesServiceReference.HelloWorldResponse JoesWebApplication.JoesServiceReference.JoesWebServiceSoap.HelloWorld(JoesWebApplication.JoesServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            JoesWebApplication.JoesServiceReference.HelloWorldRequest inValue = new JoesWebApplication.JoesServiceReference.HelloWorldRequest();
            inValue.Body = new JoesWebApplication.JoesServiceReference.HelloWorldRequestBody();
            JoesWebApplication.JoesServiceReference.HelloWorldResponse retVal = ((JoesWebApplication.JoesServiceReference.JoesWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JoesWebApplication.JoesServiceReference.HelloWorldResponse> JoesWebApplication.JoesServiceReference.JoesWebServiceSoap.HelloWorldAsync(JoesWebApplication.JoesServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<JoesWebApplication.JoesServiceReference.HelloWorldResponse> HelloWorldAsync() {
            JoesWebApplication.JoesServiceReference.HelloWorldRequest inValue = new JoesWebApplication.JoesServiceReference.HelloWorldRequest();
            inValue.Body = new JoesWebApplication.JoesServiceReference.HelloWorldRequestBody();
            return ((JoesWebApplication.JoesServiceReference.JoesWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JoesWebApplication.JoesServiceReference.HelloWorldByUserResponse JoesWebApplication.JoesServiceReference.JoesWebServiceSoap.HelloWorldByUser(JoesWebApplication.JoesServiceReference.HelloWorldByUserRequest request) {
            return base.Channel.HelloWorldByUser(request);
        }
        
        public string HelloWorldByUser(string usr, string pwd) {
            JoesWebApplication.JoesServiceReference.HelloWorldByUserRequest inValue = new JoesWebApplication.JoesServiceReference.HelloWorldByUserRequest();
            inValue.Body = new JoesWebApplication.JoesServiceReference.HelloWorldByUserRequestBody();
            inValue.Body.usr = usr;
            inValue.Body.pwd = pwd;
            JoesWebApplication.JoesServiceReference.HelloWorldByUserResponse retVal = ((JoesWebApplication.JoesServiceReference.JoesWebServiceSoap)(this)).HelloWorldByUser(inValue);
            return retVal.Body.HelloWorldByUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JoesWebApplication.JoesServiceReference.HelloWorldByUserResponse> JoesWebApplication.JoesServiceReference.JoesWebServiceSoap.HelloWorldByUserAsync(JoesWebApplication.JoesServiceReference.HelloWorldByUserRequest request) {
            return base.Channel.HelloWorldByUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<JoesWebApplication.JoesServiceReference.HelloWorldByUserResponse> HelloWorldByUserAsync(string usr, string pwd) {
            JoesWebApplication.JoesServiceReference.HelloWorldByUserRequest inValue = new JoesWebApplication.JoesServiceReference.HelloWorldByUserRequest();
            inValue.Body = new JoesWebApplication.JoesServiceReference.HelloWorldByUserRequestBody();
            inValue.Body.usr = usr;
            inValue.Body.pwd = pwd;
            return ((JoesWebApplication.JoesServiceReference.JoesWebServiceSoap)(this)).HelloWorldByUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JoesWebApplication.JoesServiceReference.HelloWorldByTokenResponse JoesWebApplication.JoesServiceReference.JoesWebServiceSoap.HelloWorldByToken(JoesWebApplication.JoesServiceReference.HelloWorldByTokenRequest request) {
            return base.Channel.HelloWorldByToken(request);
        }
        
        public string HelloWorldByToken(string authToken) {
            JoesWebApplication.JoesServiceReference.HelloWorldByTokenRequest inValue = new JoesWebApplication.JoesServiceReference.HelloWorldByTokenRequest();
            inValue.Body = new JoesWebApplication.JoesServiceReference.HelloWorldByTokenRequestBody();
            inValue.Body.authToken = authToken;
            JoesWebApplication.JoesServiceReference.HelloWorldByTokenResponse retVal = ((JoesWebApplication.JoesServiceReference.JoesWebServiceSoap)(this)).HelloWorldByToken(inValue);
            return retVal.Body.HelloWorldByTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JoesWebApplication.JoesServiceReference.HelloWorldByTokenResponse> JoesWebApplication.JoesServiceReference.JoesWebServiceSoap.HelloWorldByTokenAsync(JoesWebApplication.JoesServiceReference.HelloWorldByTokenRequest request) {
            return base.Channel.HelloWorldByTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<JoesWebApplication.JoesServiceReference.HelloWorldByTokenResponse> HelloWorldByTokenAsync(string authToken) {
            JoesWebApplication.JoesServiceReference.HelloWorldByTokenRequest inValue = new JoesWebApplication.JoesServiceReference.HelloWorldByTokenRequest();
            inValue.Body = new JoesWebApplication.JoesServiceReference.HelloWorldByTokenRequestBody();
            inValue.Body.authToken = authToken;
            return ((JoesWebApplication.JoesServiceReference.JoesWebServiceSoap)(this)).HelloWorldByTokenAsync(inValue);
        }
    }
}
