//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int Id { get; set; }
        public Nullable<int> TipoIdentificacionId { get; set; }
        public string NumeroIdentificacion { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual TipoIdentificacion TipoIdentificacion { get; set; }
    }
}
