//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LoginServiceEntities : DbContext
    {
        public LoginServiceEntities()
            : base("name=LoginServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumnoes { get; set; }
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<Profesor> Profesors { get; set; }
    
        public virtual ObjectResult<ObtenerUsuariosPorIDSP_Result> ObtenerUsuariosPorIDSP(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerUsuariosPorIDSP_Result>("ObtenerUsuariosPorIDSP", iDParameter);
        }
    
        public virtual ObjectResult<ObtenerAlumnos_Result> ObtenerAlumnos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerAlumnos_Result>("ObtenerAlumnos");
        }
    }
}
