//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormWithSomee.LoginServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginServiceReference.LoginSoap")]
    public interface LoginSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginByUserAndPassword", ReplyAction="*")]
        WebFormWithSomee.LoginServiceReference.LoginByUserAndPasswordResponse LoginByUserAndPassword(WebFormWithSomee.LoginServiceReference.LoginByUserAndPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginByUserAndPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormWithSomee.LoginServiceReference.LoginByUserAndPasswordResponse> LoginByUserAndPasswordAsync(WebFormWithSomee.LoginServiceReference.LoginByUserAndPasswordRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento token del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validarToken", ReplyAction="*")]
        WebFormWithSomee.LoginServiceReference.validarTokenResponse validarToken(WebFormWithSomee.LoginServiceReference.validarTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validarToken", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormWithSomee.LoginServiceReference.validarTokenResponse> validarTokenAsync(WebFormWithSomee.LoginServiceReference.validarTokenRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento token del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarToken", ReplyAction="*")]
        WebFormWithSomee.LoginServiceReference.eliminarTokenResponse eliminarToken(WebFormWithSomee.LoginServiceReference.eliminarTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarToken", ReplyAction="*")]
        System.Threading.Tasks.Task<WebFormWithSomee.LoginServiceReference.eliminarTokenResponse> eliminarTokenAsync(WebFormWithSomee.LoginServiceReference.eliminarTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginByUserAndPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginByUserAndPassword", Namespace="http://tempuri.org/", Order=0)]
        public WebFormWithSomee.LoginServiceReference.LoginByUserAndPasswordRequestBody Body;
        
        public LoginByUserAndPasswordRequest() {
        }
        
        public LoginByUserAndPasswordRequest(WebFormWithSomee.LoginServiceReference.LoginByUserAndPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginByUserAndPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginByUserAndPasswordRequestBody() {
        }
        
        public LoginByUserAndPasswordRequestBody(string usuario, string password) {
            this.usuario = usuario;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginByUserAndPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginByUserAndPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebFormWithSomee.LoginServiceReference.LoginByUserAndPasswordResponseBody Body;
        
        public LoginByUserAndPasswordResponse() {
        }
        
        public LoginByUserAndPasswordResponse(WebFormWithSomee.LoginServiceReference.LoginByUserAndPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginByUserAndPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginByUserAndPasswordResult;
        
        public LoginByUserAndPasswordResponseBody() {
        }
        
        public LoginByUserAndPasswordResponseBody(string LoginByUserAndPasswordResult) {
            this.LoginByUserAndPasswordResult = LoginByUserAndPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarToken", Namespace="http://tempuri.org/", Order=0)]
        public WebFormWithSomee.LoginServiceReference.validarTokenRequestBody Body;
        
        public validarTokenRequest() {
        }
        
        public validarTokenRequest(WebFormWithSomee.LoginServiceReference.validarTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class validarTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public validarTokenRequestBody() {
        }
        
        public validarTokenRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebFormWithSomee.LoginServiceReference.validarTokenResponseBody Body;
        
        public validarTokenResponse() {
        }
        
        public validarTokenResponse(WebFormWithSomee.LoginServiceReference.validarTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class validarTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool validarTokenResult;
        
        public validarTokenResponseBody() {
        }
        
        public validarTokenResponseBody(bool validarTokenResult) {
            this.validarTokenResult = validarTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarToken", Namespace="http://tempuri.org/", Order=0)]
        public WebFormWithSomee.LoginServiceReference.eliminarTokenRequestBody Body;
        
        public eliminarTokenRequest() {
        }
        
        public eliminarTokenRequest(WebFormWithSomee.LoginServiceReference.eliminarTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public eliminarTokenRequestBody() {
        }
        
        public eliminarTokenRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebFormWithSomee.LoginServiceReference.eliminarTokenResponseBody Body;
        
        public eliminarTokenResponse() {
        }
        
        public eliminarTokenResponse(WebFormWithSomee.LoginServiceReference.eliminarTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool eliminarTokenResult;
        
        public eliminarTokenResponseBody() {
        }
        
        public eliminarTokenResponseBody(bool eliminarTokenResult) {
            this.eliminarTokenResult = eliminarTokenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginSoapChannel : WebFormWithSomee.LoginServiceReference.LoginSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginSoapClient : System.ServiceModel.ClientBase<WebFormWithSomee.LoginServiceReference.LoginSoap>, WebFormWithSomee.LoginServiceReference.LoginSoap {
        
        public LoginSoapClient() {
        }
        
        public LoginSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebFormWithSomee.LoginServiceReference.LoginByUserAndPasswordResponse WebFormWithSomee.LoginServiceReference.LoginSoap.LoginByUserAndPassword(WebFormWithSomee.LoginServiceReference.LoginByUserAndPasswordRequest request) {
            return base.Channel.LoginByUserAndPassword(request);
        }
        
        public string LoginByUserAndPassword(string usuario, string password) {
            WebFormWithSomee.LoginServiceReference.LoginByUserAndPasswordRequest inValue = new WebFormWithSomee.LoginServiceReference.LoginByUserAndPasswordRequest();
            inValue.Body = new WebFormWithSomee.LoginServiceReference.LoginByUserAndPasswordRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            WebFormWithSomee.LoginServiceReference.LoginByUserAndPasswordResponse retVal = ((WebFormWithSomee.LoginServiceReference.LoginSoap)(this)).LoginByUserAndPassword(inValue);
            return retVal.Body.LoginByUserAndPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebFormWithSomee.LoginServiceReference.LoginByUserAndPasswordResponse> WebFormWithSomee.LoginServiceReference.LoginSoap.LoginByUserAndPasswordAsync(WebFormWithSomee.LoginServiceReference.LoginByUserAndPasswordRequest request) {
            return base.Channel.LoginByUserAndPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebFormWithSomee.LoginServiceReference.LoginByUserAndPasswordResponse> LoginByUserAndPasswordAsync(string usuario, string password) {
            WebFormWithSomee.LoginServiceReference.LoginByUserAndPasswordRequest inValue = new WebFormWithSomee.LoginServiceReference.LoginByUserAndPasswordRequest();
            inValue.Body = new WebFormWithSomee.LoginServiceReference.LoginByUserAndPasswordRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            return ((WebFormWithSomee.LoginServiceReference.LoginSoap)(this)).LoginByUserAndPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebFormWithSomee.LoginServiceReference.validarTokenResponse WebFormWithSomee.LoginServiceReference.LoginSoap.validarToken(WebFormWithSomee.LoginServiceReference.validarTokenRequest request) {
            return base.Channel.validarToken(request);
        }
        
        public bool validarToken(string token) {
            WebFormWithSomee.LoginServiceReference.validarTokenRequest inValue = new WebFormWithSomee.LoginServiceReference.validarTokenRequest();
            inValue.Body = new WebFormWithSomee.LoginServiceReference.validarTokenRequestBody();
            inValue.Body.token = token;
            WebFormWithSomee.LoginServiceReference.validarTokenResponse retVal = ((WebFormWithSomee.LoginServiceReference.LoginSoap)(this)).validarToken(inValue);
            return retVal.Body.validarTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebFormWithSomee.LoginServiceReference.validarTokenResponse> WebFormWithSomee.LoginServiceReference.LoginSoap.validarTokenAsync(WebFormWithSomee.LoginServiceReference.validarTokenRequest request) {
            return base.Channel.validarTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebFormWithSomee.LoginServiceReference.validarTokenResponse> validarTokenAsync(string token) {
            WebFormWithSomee.LoginServiceReference.validarTokenRequest inValue = new WebFormWithSomee.LoginServiceReference.validarTokenRequest();
            inValue.Body = new WebFormWithSomee.LoginServiceReference.validarTokenRequestBody();
            inValue.Body.token = token;
            return ((WebFormWithSomee.LoginServiceReference.LoginSoap)(this)).validarTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebFormWithSomee.LoginServiceReference.eliminarTokenResponse WebFormWithSomee.LoginServiceReference.LoginSoap.eliminarToken(WebFormWithSomee.LoginServiceReference.eliminarTokenRequest request) {
            return base.Channel.eliminarToken(request);
        }
        
        public bool eliminarToken(string token) {
            WebFormWithSomee.LoginServiceReference.eliminarTokenRequest inValue = new WebFormWithSomee.LoginServiceReference.eliminarTokenRequest();
            inValue.Body = new WebFormWithSomee.LoginServiceReference.eliminarTokenRequestBody();
            inValue.Body.token = token;
            WebFormWithSomee.LoginServiceReference.eliminarTokenResponse retVal = ((WebFormWithSomee.LoginServiceReference.LoginSoap)(this)).eliminarToken(inValue);
            return retVal.Body.eliminarTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebFormWithSomee.LoginServiceReference.eliminarTokenResponse> WebFormWithSomee.LoginServiceReference.LoginSoap.eliminarTokenAsync(WebFormWithSomee.LoginServiceReference.eliminarTokenRequest request) {
            return base.Channel.eliminarTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebFormWithSomee.LoginServiceReference.eliminarTokenResponse> eliminarTokenAsync(string token) {
            WebFormWithSomee.LoginServiceReference.eliminarTokenRequest inValue = new WebFormWithSomee.LoginServiceReference.eliminarTokenRequest();
            inValue.Body = new WebFormWithSomee.LoginServiceReference.eliminarTokenRequestBody();
            inValue.Body.token = token;
            return ((WebFormWithSomee.LoginServiceReference.LoginSoap)(this)).eliminarTokenAsync(inValue);
        }
    }
}
