//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatosSomee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int ProductoID { get; set; }
        public int ProductoCategoriaID { get; set; }
        public string Nombre { get; set; }
        public string Color { get; set; }
        public decimal Precio { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual ProductoCategoria ProductoCategoria { get; set; }
    }
}
