//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReferenceSomee {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProductoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private decimal PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoDetalleDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProductoDetalleDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        private decimal PrecioField;
        
        private System.DateTime FechaCreacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSomee.ProductosSoap")]
    public interface ProductosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerProductosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProductos", ReplyAction="*")]
        WebApplication1.ServiceReferenceSomee.ObtenerProductosResponse ObtenerProductos(WebApplication1.ServiceReferenceSomee.ObtenerProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReferenceSomee.ObtenerProductosResponse> ObtenerProductosAsync(WebApplication1.ServiceReferenceSomee.ObtenerProductosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerProductoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProducto", ReplyAction="*")]
        WebApplication1.ServiceReferenceSomee.ObtenerProductoResponse ObtenerProducto(WebApplication1.ServiceReferenceSomee.ObtenerProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReferenceSomee.ObtenerProductoResponse> ObtenerProductoAsync(WebApplication1.ServiceReferenceSomee.ObtenerProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerProductoDetalleResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProductoDetalle", ReplyAction="*")]
        WebApplication1.ServiceReferenceSomee.ObtenerProductoDetalleResponse ObtenerProductoDetalle(WebApplication1.ServiceReferenceSomee.ObtenerProductoDetalleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProductoDetalle", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReferenceSomee.ObtenerProductoDetalleResponse> ObtenerProductoDetalleAsync(WebApplication1.ServiceReferenceSomee.ObtenerProductoDetalleRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarNuevoProducto", ReplyAction="*")]
        WebApplication1.ServiceReferenceSomee.AgregarNuevoProductoResponse AgregarNuevoProducto(WebApplication1.ServiceReferenceSomee.AgregarNuevoProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarNuevoProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReferenceSomee.AgregarNuevoProductoResponse> AgregarNuevoProductoAsync(WebApplication1.ServiceReferenceSomee.AgregarNuevoProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarProducto", ReplyAction="*")]
        WebApplication1.ServiceReferenceSomee.ActualizarProductoResponse ActualizarProducto(WebApplication1.ServiceReferenceSomee.ActualizarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReferenceSomee.ActualizarProductoResponse> ActualizarProductoAsync(WebApplication1.ServiceReferenceSomee.ActualizarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarProducto", ReplyAction="*")]
        bool EliminarProducto(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarProductoAsync(int idProducto);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProductos", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReferenceSomee.ObtenerProductosRequestBody Body;
        
        public ObtenerProductosRequest() {
        }
        
        public ObtenerProductosRequest(WebApplication1.ServiceReferenceSomee.ObtenerProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerProductosRequestBody {
        
        public ObtenerProductosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProductosResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReferenceSomee.ObtenerProductosResponseBody Body;
        
        public ObtenerProductosResponse() {
        }
        
        public ObtenerProductosResponse(WebApplication1.ServiceReferenceSomee.ObtenerProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1.ServiceReferenceSomee.ProductoDTO[] ObtenerProductosResult;
        
        public ObtenerProductosResponseBody() {
        }
        
        public ObtenerProductosResponseBody(WebApplication1.ServiceReferenceSomee.ProductoDTO[] ObtenerProductosResult) {
            this.ObtenerProductosResult = ObtenerProductosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProducto", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReferenceSomee.ObtenerProductoRequestBody Body;
        
        public ObtenerProductoRequest() {
        }
        
        public ObtenerProductoRequest(WebApplication1.ServiceReferenceSomee.ObtenerProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idProducto;
        
        public ObtenerProductoRequestBody() {
        }
        
        public ObtenerProductoRequestBody(int idProducto) {
            this.idProducto = idProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReferenceSomee.ObtenerProductoResponseBody Body;
        
        public ObtenerProductoResponse() {
        }
        
        public ObtenerProductoResponse(WebApplication1.ServiceReferenceSomee.ObtenerProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1.ServiceReferenceSomee.ProductoDTO ObtenerProductoResult;
        
        public ObtenerProductoResponseBody() {
        }
        
        public ObtenerProductoResponseBody(WebApplication1.ServiceReferenceSomee.ProductoDTO ObtenerProductoResult) {
            this.ObtenerProductoResult = ObtenerProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProductoDetalleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProductoDetalle", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReferenceSomee.ObtenerProductoDetalleRequestBody Body;
        
        public ObtenerProductoDetalleRequest() {
        }
        
        public ObtenerProductoDetalleRequest(WebApplication1.ServiceReferenceSomee.ObtenerProductoDetalleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerProductoDetalleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idProducto;
        
        public ObtenerProductoDetalleRequestBody() {
        }
        
        public ObtenerProductoDetalleRequestBody(int idProducto) {
            this.idProducto = idProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProductoDetalleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProductoDetalleResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReferenceSomee.ObtenerProductoDetalleResponseBody Body;
        
        public ObtenerProductoDetalleResponse() {
        }
        
        public ObtenerProductoDetalleResponse(WebApplication1.ServiceReferenceSomee.ObtenerProductoDetalleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerProductoDetalleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1.ServiceReferenceSomee.ProductoDetalleDTO ObtenerProductoDetalleResult;
        
        public ObtenerProductoDetalleResponseBody() {
        }
        
        public ObtenerProductoDetalleResponseBody(WebApplication1.ServiceReferenceSomee.ProductoDetalleDTO ObtenerProductoDetalleResult) {
            this.ObtenerProductoDetalleResult = ObtenerProductoDetalleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarNuevoProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarNuevoProducto", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReferenceSomee.AgregarNuevoProductoRequestBody Body;
        
        public AgregarNuevoProductoRequest() {
        }
        
        public AgregarNuevoProductoRequest(WebApplication1.ServiceReferenceSomee.AgregarNuevoProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarNuevoProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int categoria;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string color;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal precio;
        
        public AgregarNuevoProductoRequestBody() {
        }
        
        public AgregarNuevoProductoRequestBody(string nombre, int categoria, string color, decimal precio) {
            this.nombre = nombre;
            this.categoria = categoria;
            this.color = color;
            this.precio = precio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarNuevoProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarNuevoProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReferenceSomee.AgregarNuevoProductoResponseBody Body;
        
        public AgregarNuevoProductoResponse() {
        }
        
        public AgregarNuevoProductoResponse(WebApplication1.ServiceReferenceSomee.AgregarNuevoProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarNuevoProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AgregarNuevoProductoResult;
        
        public AgregarNuevoProductoResponseBody() {
        }
        
        public AgregarNuevoProductoResponseBody(bool AgregarNuevoProductoResult) {
            this.AgregarNuevoProductoResult = AgregarNuevoProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarProducto", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReferenceSomee.ActualizarProductoRequestBody Body;
        
        public ActualizarProductoRequest() {
        }
        
        public ActualizarProductoRequest(WebApplication1.ServiceReferenceSomee.ActualizarProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idProducto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int categoria;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string color;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal precio;
        
        public ActualizarProductoRequestBody() {
        }
        
        public ActualizarProductoRequestBody(int idProducto, string nombre, int categoria, string color, decimal precio) {
            this.idProducto = idProducto;
            this.nombre = nombre;
            this.categoria = categoria;
            this.color = color;
            this.precio = precio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.ServiceReferenceSomee.ActualizarProductoResponseBody Body;
        
        public ActualizarProductoResponse() {
        }
        
        public ActualizarProductoResponse(WebApplication1.ServiceReferenceSomee.ActualizarProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarProductoResult;
        
        public ActualizarProductoResponseBody() {
        }
        
        public ActualizarProductoResponseBody(bool ActualizarProductoResult) {
            this.ActualizarProductoResult = ActualizarProductoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductosSoapChannel : WebApplication1.ServiceReferenceSomee.ProductosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductosSoapClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReferenceSomee.ProductosSoap>, WebApplication1.ServiceReferenceSomee.ProductosSoap {
        
        public ProductosSoapClient() {
        }
        
        public ProductosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReferenceSomee.ObtenerProductosResponse WebApplication1.ServiceReferenceSomee.ProductosSoap.ObtenerProductos(WebApplication1.ServiceReferenceSomee.ObtenerProductosRequest request) {
            return base.Channel.ObtenerProductos(request);
        }
        
        public WebApplication1.ServiceReferenceSomee.ProductoDTO[] ObtenerProductos() {
            WebApplication1.ServiceReferenceSomee.ObtenerProductosRequest inValue = new WebApplication1.ServiceReferenceSomee.ObtenerProductosRequest();
            inValue.Body = new WebApplication1.ServiceReferenceSomee.ObtenerProductosRequestBody();
            WebApplication1.ServiceReferenceSomee.ObtenerProductosResponse retVal = ((WebApplication1.ServiceReferenceSomee.ProductosSoap)(this)).ObtenerProductos(inValue);
            return retVal.Body.ObtenerProductosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReferenceSomee.ObtenerProductosResponse> WebApplication1.ServiceReferenceSomee.ProductosSoap.ObtenerProductosAsync(WebApplication1.ServiceReferenceSomee.ObtenerProductosRequest request) {
            return base.Channel.ObtenerProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReferenceSomee.ObtenerProductosResponse> ObtenerProductosAsync() {
            WebApplication1.ServiceReferenceSomee.ObtenerProductosRequest inValue = new WebApplication1.ServiceReferenceSomee.ObtenerProductosRequest();
            inValue.Body = new WebApplication1.ServiceReferenceSomee.ObtenerProductosRequestBody();
            return ((WebApplication1.ServiceReferenceSomee.ProductosSoap)(this)).ObtenerProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReferenceSomee.ObtenerProductoResponse WebApplication1.ServiceReferenceSomee.ProductosSoap.ObtenerProducto(WebApplication1.ServiceReferenceSomee.ObtenerProductoRequest request) {
            return base.Channel.ObtenerProducto(request);
        }
        
        public WebApplication1.ServiceReferenceSomee.ProductoDTO ObtenerProducto(int idProducto) {
            WebApplication1.ServiceReferenceSomee.ObtenerProductoRequest inValue = new WebApplication1.ServiceReferenceSomee.ObtenerProductoRequest();
            inValue.Body = new WebApplication1.ServiceReferenceSomee.ObtenerProductoRequestBody();
            inValue.Body.idProducto = idProducto;
            WebApplication1.ServiceReferenceSomee.ObtenerProductoResponse retVal = ((WebApplication1.ServiceReferenceSomee.ProductosSoap)(this)).ObtenerProducto(inValue);
            return retVal.Body.ObtenerProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReferenceSomee.ObtenerProductoResponse> WebApplication1.ServiceReferenceSomee.ProductosSoap.ObtenerProductoAsync(WebApplication1.ServiceReferenceSomee.ObtenerProductoRequest request) {
            return base.Channel.ObtenerProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReferenceSomee.ObtenerProductoResponse> ObtenerProductoAsync(int idProducto) {
            WebApplication1.ServiceReferenceSomee.ObtenerProductoRequest inValue = new WebApplication1.ServiceReferenceSomee.ObtenerProductoRequest();
            inValue.Body = new WebApplication1.ServiceReferenceSomee.ObtenerProductoRequestBody();
            inValue.Body.idProducto = idProducto;
            return ((WebApplication1.ServiceReferenceSomee.ProductosSoap)(this)).ObtenerProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReferenceSomee.ObtenerProductoDetalleResponse WebApplication1.ServiceReferenceSomee.ProductosSoap.ObtenerProductoDetalle(WebApplication1.ServiceReferenceSomee.ObtenerProductoDetalleRequest request) {
            return base.Channel.ObtenerProductoDetalle(request);
        }
        
        public WebApplication1.ServiceReferenceSomee.ProductoDetalleDTO ObtenerProductoDetalle(int idProducto) {
            WebApplication1.ServiceReferenceSomee.ObtenerProductoDetalleRequest inValue = new WebApplication1.ServiceReferenceSomee.ObtenerProductoDetalleRequest();
            inValue.Body = new WebApplication1.ServiceReferenceSomee.ObtenerProductoDetalleRequestBody();
            inValue.Body.idProducto = idProducto;
            WebApplication1.ServiceReferenceSomee.ObtenerProductoDetalleResponse retVal = ((WebApplication1.ServiceReferenceSomee.ProductosSoap)(this)).ObtenerProductoDetalle(inValue);
            return retVal.Body.ObtenerProductoDetalleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReferenceSomee.ObtenerProductoDetalleResponse> WebApplication1.ServiceReferenceSomee.ProductosSoap.ObtenerProductoDetalleAsync(WebApplication1.ServiceReferenceSomee.ObtenerProductoDetalleRequest request) {
            return base.Channel.ObtenerProductoDetalleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReferenceSomee.ObtenerProductoDetalleResponse> ObtenerProductoDetalleAsync(int idProducto) {
            WebApplication1.ServiceReferenceSomee.ObtenerProductoDetalleRequest inValue = new WebApplication1.ServiceReferenceSomee.ObtenerProductoDetalleRequest();
            inValue.Body = new WebApplication1.ServiceReferenceSomee.ObtenerProductoDetalleRequestBody();
            inValue.Body.idProducto = idProducto;
            return ((WebApplication1.ServiceReferenceSomee.ProductosSoap)(this)).ObtenerProductoDetalleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReferenceSomee.AgregarNuevoProductoResponse WebApplication1.ServiceReferenceSomee.ProductosSoap.AgregarNuevoProducto(WebApplication1.ServiceReferenceSomee.AgregarNuevoProductoRequest request) {
            return base.Channel.AgregarNuevoProducto(request);
        }
        
        public bool AgregarNuevoProducto(string nombre, int categoria, string color, decimal precio) {
            WebApplication1.ServiceReferenceSomee.AgregarNuevoProductoRequest inValue = new WebApplication1.ServiceReferenceSomee.AgregarNuevoProductoRequest();
            inValue.Body = new WebApplication1.ServiceReferenceSomee.AgregarNuevoProductoRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.categoria = categoria;
            inValue.Body.color = color;
            inValue.Body.precio = precio;
            WebApplication1.ServiceReferenceSomee.AgregarNuevoProductoResponse retVal = ((WebApplication1.ServiceReferenceSomee.ProductosSoap)(this)).AgregarNuevoProducto(inValue);
            return retVal.Body.AgregarNuevoProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReferenceSomee.AgregarNuevoProductoResponse> WebApplication1.ServiceReferenceSomee.ProductosSoap.AgregarNuevoProductoAsync(WebApplication1.ServiceReferenceSomee.AgregarNuevoProductoRequest request) {
            return base.Channel.AgregarNuevoProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReferenceSomee.AgregarNuevoProductoResponse> AgregarNuevoProductoAsync(string nombre, int categoria, string color, decimal precio) {
            WebApplication1.ServiceReferenceSomee.AgregarNuevoProductoRequest inValue = new WebApplication1.ServiceReferenceSomee.AgregarNuevoProductoRequest();
            inValue.Body = new WebApplication1.ServiceReferenceSomee.AgregarNuevoProductoRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.categoria = categoria;
            inValue.Body.color = color;
            inValue.Body.precio = precio;
            return ((WebApplication1.ServiceReferenceSomee.ProductosSoap)(this)).AgregarNuevoProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReferenceSomee.ActualizarProductoResponse WebApplication1.ServiceReferenceSomee.ProductosSoap.ActualizarProducto(WebApplication1.ServiceReferenceSomee.ActualizarProductoRequest request) {
            return base.Channel.ActualizarProducto(request);
        }
        
        public bool ActualizarProducto(int idProducto, string nombre, int categoria, string color, decimal precio) {
            WebApplication1.ServiceReferenceSomee.ActualizarProductoRequest inValue = new WebApplication1.ServiceReferenceSomee.ActualizarProductoRequest();
            inValue.Body = new WebApplication1.ServiceReferenceSomee.ActualizarProductoRequestBody();
            inValue.Body.idProducto = idProducto;
            inValue.Body.nombre = nombre;
            inValue.Body.categoria = categoria;
            inValue.Body.color = color;
            inValue.Body.precio = precio;
            WebApplication1.ServiceReferenceSomee.ActualizarProductoResponse retVal = ((WebApplication1.ServiceReferenceSomee.ProductosSoap)(this)).ActualizarProducto(inValue);
            return retVal.Body.ActualizarProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReferenceSomee.ActualizarProductoResponse> WebApplication1.ServiceReferenceSomee.ProductosSoap.ActualizarProductoAsync(WebApplication1.ServiceReferenceSomee.ActualizarProductoRequest request) {
            return base.Channel.ActualizarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReferenceSomee.ActualizarProductoResponse> ActualizarProductoAsync(int idProducto, string nombre, int categoria, string color, decimal precio) {
            WebApplication1.ServiceReferenceSomee.ActualizarProductoRequest inValue = new WebApplication1.ServiceReferenceSomee.ActualizarProductoRequest();
            inValue.Body = new WebApplication1.ServiceReferenceSomee.ActualizarProductoRequestBody();
            inValue.Body.idProducto = idProducto;
            inValue.Body.nombre = nombre;
            inValue.Body.categoria = categoria;
            inValue.Body.color = color;
            inValue.Body.precio = precio;
            return ((WebApplication1.ServiceReferenceSomee.ProductosSoap)(this)).ActualizarProductoAsync(inValue);
        }
        
        public bool EliminarProducto(int idProducto) {
            return base.Channel.EliminarProducto(idProducto);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarProductoAsync(int idProducto) {
            return base.Channel.EliminarProductoAsync(idProducto);
        }
    }
}
