//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestServicios.ServiceReferenceProductos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProductoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private decimal PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoDetalleDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProductoDetalleDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        private decimal PrecioField;
        
        private System.DateTime FechaCreacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceProductos.ProductosSoap")]
    public interface ProductosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerProductosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProductos", ReplyAction="*")]
        TestServicios.ServiceReferenceProductos.ObtenerProductosResponse ObtenerProductos(TestServicios.ServiceReferenceProductos.ObtenerProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<TestServicios.ServiceReferenceProductos.ObtenerProductosResponse> ObtenerProductosAsync(TestServicios.ServiceReferenceProductos.ObtenerProductosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerProductoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProducto", ReplyAction="*")]
        TestServicios.ServiceReferenceProductos.ObtenerProductoResponse ObtenerProducto(TestServicios.ServiceReferenceProductos.ObtenerProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<TestServicios.ServiceReferenceProductos.ObtenerProductoResponse> ObtenerProductoAsync(TestServicios.ServiceReferenceProductos.ObtenerProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerProductoDetalleResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProductoDetalle", ReplyAction="*")]
        TestServicios.ServiceReferenceProductos.ObtenerProductoDetalleResponse ObtenerProductoDetalle(TestServicios.ServiceReferenceProductos.ObtenerProductoDetalleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProductoDetalle", ReplyAction="*")]
        System.Threading.Tasks.Task<TestServicios.ServiceReferenceProductos.ObtenerProductoDetalleResponse> ObtenerProductoDetalleAsync(TestServicios.ServiceReferenceProductos.ObtenerProductoDetalleRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarNuevoProducto", ReplyAction="*")]
        TestServicios.ServiceReferenceProductos.AgregarNuevoProductoResponse AgregarNuevoProducto(TestServicios.ServiceReferenceProductos.AgregarNuevoProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarNuevoProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<TestServicios.ServiceReferenceProductos.AgregarNuevoProductoResponse> AgregarNuevoProductoAsync(TestServicios.ServiceReferenceProductos.AgregarNuevoProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarProducto", ReplyAction="*")]
        TestServicios.ServiceReferenceProductos.ActualizarProductoResponse ActualizarProducto(TestServicios.ServiceReferenceProductos.ActualizarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<TestServicios.ServiceReferenceProductos.ActualizarProductoResponse> ActualizarProductoAsync(TestServicios.ServiceReferenceProductos.ActualizarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarProducto", ReplyAction="*")]
        bool EliminarProducto(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarProductoAsync(int idProducto);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProductos", Namespace="http://tempuri.org/", Order=0)]
        public TestServicios.ServiceReferenceProductos.ObtenerProductosRequestBody Body;
        
        public ObtenerProductosRequest() {
        }
        
        public ObtenerProductosRequest(TestServicios.ServiceReferenceProductos.ObtenerProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerProductosRequestBody {
        
        public ObtenerProductosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProductosResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestServicios.ServiceReferenceProductos.ObtenerProductosResponseBody Body;
        
        public ObtenerProductosResponse() {
        }
        
        public ObtenerProductosResponse(TestServicios.ServiceReferenceProductos.ObtenerProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestServicios.ServiceReferenceProductos.ProductoDTO[] ObtenerProductosResult;
        
        public ObtenerProductosResponseBody() {
        }
        
        public ObtenerProductosResponseBody(TestServicios.ServiceReferenceProductos.ProductoDTO[] ObtenerProductosResult) {
            this.ObtenerProductosResult = ObtenerProductosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProducto", Namespace="http://tempuri.org/", Order=0)]
        public TestServicios.ServiceReferenceProductos.ObtenerProductoRequestBody Body;
        
        public ObtenerProductoRequest() {
        }
        
        public ObtenerProductoRequest(TestServicios.ServiceReferenceProductos.ObtenerProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idProducto;
        
        public ObtenerProductoRequestBody() {
        }
        
        public ObtenerProductoRequestBody(int idProducto) {
            this.idProducto = idProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestServicios.ServiceReferenceProductos.ObtenerProductoResponseBody Body;
        
        public ObtenerProductoResponse() {
        }
        
        public ObtenerProductoResponse(TestServicios.ServiceReferenceProductos.ObtenerProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestServicios.ServiceReferenceProductos.ProductoDTO ObtenerProductoResult;
        
        public ObtenerProductoResponseBody() {
        }
        
        public ObtenerProductoResponseBody(TestServicios.ServiceReferenceProductos.ProductoDTO ObtenerProductoResult) {
            this.ObtenerProductoResult = ObtenerProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProductoDetalleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProductoDetalle", Namespace="http://tempuri.org/", Order=0)]
        public TestServicios.ServiceReferenceProductos.ObtenerProductoDetalleRequestBody Body;
        
        public ObtenerProductoDetalleRequest() {
        }
        
        public ObtenerProductoDetalleRequest(TestServicios.ServiceReferenceProductos.ObtenerProductoDetalleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerProductoDetalleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idProducto;
        
        public ObtenerProductoDetalleRequestBody() {
        }
        
        public ObtenerProductoDetalleRequestBody(int idProducto) {
            this.idProducto = idProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProductoDetalleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProductoDetalleResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestServicios.ServiceReferenceProductos.ObtenerProductoDetalleResponseBody Body;
        
        public ObtenerProductoDetalleResponse() {
        }
        
        public ObtenerProductoDetalleResponse(TestServicios.ServiceReferenceProductos.ObtenerProductoDetalleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerProductoDetalleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestServicios.ServiceReferenceProductos.ProductoDetalleDTO ObtenerProductoDetalleResult;
        
        public ObtenerProductoDetalleResponseBody() {
        }
        
        public ObtenerProductoDetalleResponseBody(TestServicios.ServiceReferenceProductos.ProductoDetalleDTO ObtenerProductoDetalleResult) {
            this.ObtenerProductoDetalleResult = ObtenerProductoDetalleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarNuevoProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarNuevoProducto", Namespace="http://tempuri.org/", Order=0)]
        public TestServicios.ServiceReferenceProductos.AgregarNuevoProductoRequestBody Body;
        
        public AgregarNuevoProductoRequest() {
        }
        
        public AgregarNuevoProductoRequest(TestServicios.ServiceReferenceProductos.AgregarNuevoProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarNuevoProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int categoria;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string color;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal precio;
        
        public AgregarNuevoProductoRequestBody() {
        }
        
        public AgregarNuevoProductoRequestBody(string nombre, int categoria, string color, decimal precio) {
            this.nombre = nombre;
            this.categoria = categoria;
            this.color = color;
            this.precio = precio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarNuevoProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarNuevoProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestServicios.ServiceReferenceProductos.AgregarNuevoProductoResponseBody Body;
        
        public AgregarNuevoProductoResponse() {
        }
        
        public AgregarNuevoProductoResponse(TestServicios.ServiceReferenceProductos.AgregarNuevoProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarNuevoProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AgregarNuevoProductoResult;
        
        public AgregarNuevoProductoResponseBody() {
        }
        
        public AgregarNuevoProductoResponseBody(bool AgregarNuevoProductoResult) {
            this.AgregarNuevoProductoResult = AgregarNuevoProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarProducto", Namespace="http://tempuri.org/", Order=0)]
        public TestServicios.ServiceReferenceProductos.ActualizarProductoRequestBody Body;
        
        public ActualizarProductoRequest() {
        }
        
        public ActualizarProductoRequest(TestServicios.ServiceReferenceProductos.ActualizarProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idProducto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int categoria;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string color;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal precio;
        
        public ActualizarProductoRequestBody() {
        }
        
        public ActualizarProductoRequestBody(int idProducto, string nombre, int categoria, string color, decimal precio) {
            this.idProducto = idProducto;
            this.nombre = nombre;
            this.categoria = categoria;
            this.color = color;
            this.precio = precio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestServicios.ServiceReferenceProductos.ActualizarProductoResponseBody Body;
        
        public ActualizarProductoResponse() {
        }
        
        public ActualizarProductoResponse(TestServicios.ServiceReferenceProductos.ActualizarProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarProductoResult;
        
        public ActualizarProductoResponseBody() {
        }
        
        public ActualizarProductoResponseBody(bool ActualizarProductoResult) {
            this.ActualizarProductoResult = ActualizarProductoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductosSoapChannel : TestServicios.ServiceReferenceProductos.ProductosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductosSoapClient : System.ServiceModel.ClientBase<TestServicios.ServiceReferenceProductos.ProductosSoap>, TestServicios.ServiceReferenceProductos.ProductosSoap {
        
        public ProductosSoapClient() {
        }
        
        public ProductosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestServicios.ServiceReferenceProductos.ObtenerProductosResponse TestServicios.ServiceReferenceProductos.ProductosSoap.ObtenerProductos(TestServicios.ServiceReferenceProductos.ObtenerProductosRequest request) {
            return base.Channel.ObtenerProductos(request);
        }
        
        public TestServicios.ServiceReferenceProductos.ProductoDTO[] ObtenerProductos() {
            TestServicios.ServiceReferenceProductos.ObtenerProductosRequest inValue = new TestServicios.ServiceReferenceProductos.ObtenerProductosRequest();
            inValue.Body = new TestServicios.ServiceReferenceProductos.ObtenerProductosRequestBody();
            TestServicios.ServiceReferenceProductos.ObtenerProductosResponse retVal = ((TestServicios.ServiceReferenceProductos.ProductosSoap)(this)).ObtenerProductos(inValue);
            return retVal.Body.ObtenerProductosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestServicios.ServiceReferenceProductos.ObtenerProductosResponse> TestServicios.ServiceReferenceProductos.ProductosSoap.ObtenerProductosAsync(TestServicios.ServiceReferenceProductos.ObtenerProductosRequest request) {
            return base.Channel.ObtenerProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestServicios.ServiceReferenceProductos.ObtenerProductosResponse> ObtenerProductosAsync() {
            TestServicios.ServiceReferenceProductos.ObtenerProductosRequest inValue = new TestServicios.ServiceReferenceProductos.ObtenerProductosRequest();
            inValue.Body = new TestServicios.ServiceReferenceProductos.ObtenerProductosRequestBody();
            return ((TestServicios.ServiceReferenceProductos.ProductosSoap)(this)).ObtenerProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestServicios.ServiceReferenceProductos.ObtenerProductoResponse TestServicios.ServiceReferenceProductos.ProductosSoap.ObtenerProducto(TestServicios.ServiceReferenceProductos.ObtenerProductoRequest request) {
            return base.Channel.ObtenerProducto(request);
        }
        
        public TestServicios.ServiceReferenceProductos.ProductoDTO ObtenerProducto(int idProducto) {
            TestServicios.ServiceReferenceProductos.ObtenerProductoRequest inValue = new TestServicios.ServiceReferenceProductos.ObtenerProductoRequest();
            inValue.Body = new TestServicios.ServiceReferenceProductos.ObtenerProductoRequestBody();
            inValue.Body.idProducto = idProducto;
            TestServicios.ServiceReferenceProductos.ObtenerProductoResponse retVal = ((TestServicios.ServiceReferenceProductos.ProductosSoap)(this)).ObtenerProducto(inValue);
            return retVal.Body.ObtenerProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestServicios.ServiceReferenceProductos.ObtenerProductoResponse> TestServicios.ServiceReferenceProductos.ProductosSoap.ObtenerProductoAsync(TestServicios.ServiceReferenceProductos.ObtenerProductoRequest request) {
            return base.Channel.ObtenerProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestServicios.ServiceReferenceProductos.ObtenerProductoResponse> ObtenerProductoAsync(int idProducto) {
            TestServicios.ServiceReferenceProductos.ObtenerProductoRequest inValue = new TestServicios.ServiceReferenceProductos.ObtenerProductoRequest();
            inValue.Body = new TestServicios.ServiceReferenceProductos.ObtenerProductoRequestBody();
            inValue.Body.idProducto = idProducto;
            return ((TestServicios.ServiceReferenceProductos.ProductosSoap)(this)).ObtenerProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestServicios.ServiceReferenceProductos.ObtenerProductoDetalleResponse TestServicios.ServiceReferenceProductos.ProductosSoap.ObtenerProductoDetalle(TestServicios.ServiceReferenceProductos.ObtenerProductoDetalleRequest request) {
            return base.Channel.ObtenerProductoDetalle(request);
        }
        
        public TestServicios.ServiceReferenceProductos.ProductoDetalleDTO ObtenerProductoDetalle(int idProducto) {
            TestServicios.ServiceReferenceProductos.ObtenerProductoDetalleRequest inValue = new TestServicios.ServiceReferenceProductos.ObtenerProductoDetalleRequest();
            inValue.Body = new TestServicios.ServiceReferenceProductos.ObtenerProductoDetalleRequestBody();
            inValue.Body.idProducto = idProducto;
            TestServicios.ServiceReferenceProductos.ObtenerProductoDetalleResponse retVal = ((TestServicios.ServiceReferenceProductos.ProductosSoap)(this)).ObtenerProductoDetalle(inValue);
            return retVal.Body.ObtenerProductoDetalleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestServicios.ServiceReferenceProductos.ObtenerProductoDetalleResponse> TestServicios.ServiceReferenceProductos.ProductosSoap.ObtenerProductoDetalleAsync(TestServicios.ServiceReferenceProductos.ObtenerProductoDetalleRequest request) {
            return base.Channel.ObtenerProductoDetalleAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestServicios.ServiceReferenceProductos.ObtenerProductoDetalleResponse> ObtenerProductoDetalleAsync(int idProducto) {
            TestServicios.ServiceReferenceProductos.ObtenerProductoDetalleRequest inValue = new TestServicios.ServiceReferenceProductos.ObtenerProductoDetalleRequest();
            inValue.Body = new TestServicios.ServiceReferenceProductos.ObtenerProductoDetalleRequestBody();
            inValue.Body.idProducto = idProducto;
            return ((TestServicios.ServiceReferenceProductos.ProductosSoap)(this)).ObtenerProductoDetalleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestServicios.ServiceReferenceProductos.AgregarNuevoProductoResponse TestServicios.ServiceReferenceProductos.ProductosSoap.AgregarNuevoProducto(TestServicios.ServiceReferenceProductos.AgregarNuevoProductoRequest request) {
            return base.Channel.AgregarNuevoProducto(request);
        }
        
        public bool AgregarNuevoProducto(string nombre, int categoria, string color, decimal precio) {
            TestServicios.ServiceReferenceProductos.AgregarNuevoProductoRequest inValue = new TestServicios.ServiceReferenceProductos.AgregarNuevoProductoRequest();
            inValue.Body = new TestServicios.ServiceReferenceProductos.AgregarNuevoProductoRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.categoria = categoria;
            inValue.Body.color = color;
            inValue.Body.precio = precio;
            TestServicios.ServiceReferenceProductos.AgregarNuevoProductoResponse retVal = ((TestServicios.ServiceReferenceProductos.ProductosSoap)(this)).AgregarNuevoProducto(inValue);
            return retVal.Body.AgregarNuevoProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestServicios.ServiceReferenceProductos.AgregarNuevoProductoResponse> TestServicios.ServiceReferenceProductos.ProductosSoap.AgregarNuevoProductoAsync(TestServicios.ServiceReferenceProductos.AgregarNuevoProductoRequest request) {
            return base.Channel.AgregarNuevoProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestServicios.ServiceReferenceProductos.AgregarNuevoProductoResponse> AgregarNuevoProductoAsync(string nombre, int categoria, string color, decimal precio) {
            TestServicios.ServiceReferenceProductos.AgregarNuevoProductoRequest inValue = new TestServicios.ServiceReferenceProductos.AgregarNuevoProductoRequest();
            inValue.Body = new TestServicios.ServiceReferenceProductos.AgregarNuevoProductoRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.categoria = categoria;
            inValue.Body.color = color;
            inValue.Body.precio = precio;
            return ((TestServicios.ServiceReferenceProductos.ProductosSoap)(this)).AgregarNuevoProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestServicios.ServiceReferenceProductos.ActualizarProductoResponse TestServicios.ServiceReferenceProductos.ProductosSoap.ActualizarProducto(TestServicios.ServiceReferenceProductos.ActualizarProductoRequest request) {
            return base.Channel.ActualizarProducto(request);
        }
        
        public bool ActualizarProducto(int idProducto, string nombre, int categoria, string color, decimal precio) {
            TestServicios.ServiceReferenceProductos.ActualizarProductoRequest inValue = new TestServicios.ServiceReferenceProductos.ActualizarProductoRequest();
            inValue.Body = new TestServicios.ServiceReferenceProductos.ActualizarProductoRequestBody();
            inValue.Body.idProducto = idProducto;
            inValue.Body.nombre = nombre;
            inValue.Body.categoria = categoria;
            inValue.Body.color = color;
            inValue.Body.precio = precio;
            TestServicios.ServiceReferenceProductos.ActualizarProductoResponse retVal = ((TestServicios.ServiceReferenceProductos.ProductosSoap)(this)).ActualizarProducto(inValue);
            return retVal.Body.ActualizarProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestServicios.ServiceReferenceProductos.ActualizarProductoResponse> TestServicios.ServiceReferenceProductos.ProductosSoap.ActualizarProductoAsync(TestServicios.ServiceReferenceProductos.ActualizarProductoRequest request) {
            return base.Channel.ActualizarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestServicios.ServiceReferenceProductos.ActualizarProductoResponse> ActualizarProductoAsync(int idProducto, string nombre, int categoria, string color, decimal precio) {
            TestServicios.ServiceReferenceProductos.ActualizarProductoRequest inValue = new TestServicios.ServiceReferenceProductos.ActualizarProductoRequest();
            inValue.Body = new TestServicios.ServiceReferenceProductos.ActualizarProductoRequestBody();
            inValue.Body.idProducto = idProducto;
            inValue.Body.nombre = nombre;
            inValue.Body.categoria = categoria;
            inValue.Body.color = color;
            inValue.Body.precio = precio;
            return ((TestServicios.ServiceReferenceProductos.ProductosSoap)(this)).ActualizarProductoAsync(inValue);
        }
        
        public bool EliminarProducto(int idProducto) {
            return base.Channel.EliminarProducto(idProducto);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarProductoAsync(int idProducto) {
            return base.Channel.EliminarProductoAsync(idProducto);
        }
    }
}
